INSERT INTO INVESTOR (FULLNAME, AGE, EMAIL, CONTACTNUMBER) VALUES ('Sam Smith', 35, 'mzwilidev@gmail.com', '083 568 0000');
INSERT INTO INVESTMENT (TYPE, NAME, BALANCE) VALUES ('Savings', 'Moment Fund', 100000);
INSERT INTO INVESTMENT (TYPE, NAME, BALANCE) VALUES ('Retirement', 'Ned Trust', 1705370);