CREATE TABLE INVESTOR (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    FULLNAME VARCHAR(255) NOT NULL,
    AGE INTEGER NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CONTACTNUMBER VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE INVESTMENT (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TYPE VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    BALANCE BIGINT NOT NULL,
    PRIMARY KEY (ID)
);